### ISSUE TITLE
matching nucleotides from a fasta file 

### ISSUE THREAD

**Issue by PromitaBose** [BoutrosLaboratory/bamql#10]
Hello 
Is it possible to match user provided sequences to reads in a bam file and restrict the matching to read edges only?

**Comment by clalansingh** [comment]
Hi,

At the moment this is not possible in the current implementation as there is no method of comparing sequences relative to read position, right now we only support genomic position. It is something that we will consider including in a future release, but we don't have the bandwidth to address at the moment.

Thank you for your interest in our software.
