### ISSUE TITLE
Filter on SAM tags

### ISSUE THREAD

**Issue by sjackman** [BoutrosLaboratory/bamql#11]
Can `bamql` filter on SAM tags, such as `AS:i`, `NM:i`, and `BX:Z`?

**Comment by apmasell** [comment]
Yes. These are the `aux` family instructions. For `:i` tags, use `aux_int` (_e.g._, `aux_int(AS)`). For `:Z`, use `aux_str` (_e.g._, `aux_str(BX)`). There's also `aux_dbl` for floating-point numbers.

**Comment by sjackman** [comment]
Excellent! Thanks, Andre.
