### ISSUE TITLE
llvm not found but present

### ISSUE THREAD

**Issue by brobr** [BoutrosLaboratory/bamql#13]
Hi, I was going to try bamql but could not compile the software:

`configure: error: We could not detect the llvm libraries make sure that llvm-config is on your path or specified by --with-llvm.
`

however, llvm is present:
`bash-4.4# which llvm-config`
`/usr/bin/llvm-config
`

`bash-4.4# llvm-config --version`
`6.0.1
` 

It looks from the trace that llvm is supposed to be between 3.4 and 4; which is not the case on current Slackware linux:

`
which: no llvm-config-4.0 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.9 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.8 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.7 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.6 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.5 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
which: no llvm-config-3.4 in (/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin)
`

hth

**Comment by brobr** [comment]
Thanks for the prompt reply. 

With that configure-option it still fails and I get this in the config.log:

`configure:16154: checking can compile with and link with llvm(core)
configure:16177: g++ -o conftest -O2 -fPIC  -I/usr/include -O2 -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -ffunction-sections -fdata-sections -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -L/usr/lib64  conftest.cpp -lLLVM-6.0    >&5
g++: error: unrecognized command line option '-Wcovered-switch-default'; did you mean '-Wno-switch-default'?
g++: error: unrecognized command line option '-Wstring-conversion'; did you mean '-Wint-conversion'?
configure:16177: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "bamql"`

**Comment by apmasell** [comment]
It looks like the compiler used to compile the LLVM library is different from the one you are currently using and `llvm-config` is outputting flags it can't cope with. You should probably file a bug with your package maintainer. You can work around it by doing this:

```
cat > llvm-config-mangled <<EOI
#!/bin/sh
llvm-config "\$@" | sed -e s/-Wcovered-switch-default//g
EOI
chmod a+x llvm-config-mangled
./configure --with-llvm=$(pwd)/llvm-config-mangled
```

**Comment by brobr** [comment]
Thanks, that worked (i.e. compilation started) but only after mangling llvm a bit more than you proposed.. Based on the error-messages, I also took out -Wstringconversion  and -Werror=unguarded-availability-new; if this could result in something not working properly, please let me know:

`
### with llvm-mangled3
#!/bin/sh
/usr/bin/llvm-config "\$@" | sed -e s/-Werror=unguarded-availability-new//g | \
sed -e s/-Wcovered-switch-default//g  | sed -e s/-Wstring-conversion//g


### with llvm-mangled2
#!/bin/sh
/usr/bin/llvm-config "\$@" | sed -e s/-Wcovered-switch-default//g  | sed -e s/-Wstring-conversion//g

#### config.log:
configure:16154: checking can compile with and link with llvm(core)
configure:16177: g++ -o conftest -O2 -fPIC  -I/usr/include -O2 -fPIC -fPIC -fvis
ibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std
=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-fiel
d-initializers -pedantic -Wno-long-long  -Wnon-virtual-dtor -Wdelete-non-virtual
-dtor  -ffunction-sections -fdata-sections -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC
_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -L/usr/lib64  con
ftest.cpp -lLLVM-6.0    >&5
cc1plus: error: -Werror=unguarded-availability-new: no option -Wunguarded-availa
bility-new


### with llvm-mangled
#!/bin/sh
/usr/bin/llvm-config "\$@" | sed -e s/-Wcovered-switch-default//g 

#### config.log
configure:16154: checking can compile with and link with llvm(core)
configure:16177: g++ -o conftest -O2 -fPIC  -I/usr/include -O2 -fPIC -fPIC -fvis
ibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std
=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-fiel
d-initializers -pedantic -Wno-long-long  -Wnon-virtual-dtor -Wdelete-non-virtual
-dtor -Wstring-conversion -ffunction-sections -fdata-sections -O3 -DNDEBUG   -D_
GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
  -L/usr/lib64  conftest.cpp -lLLVM-6.0    >&5
g++: error: unrecognized command line option '-Wstring-conversion'; did you mean
 '-Wint-conversion'?

### with normal llvm:
#### config.log
configure:16154: checking can compile with and link with llvm(core)
configure:16177: g++ -o conftest -O2 -fPIC  -I/usr/include -O2 -fPIC -fPIC -fvis
ibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std
=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-fiel
d-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-d
tor -Wdelete-non-virtual-dtor -Wstring-conversion -ffunction-sections -fdata-sec
tions -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACR
OS -D__STDC_LIMIT_MACROS  -L/usr/lib64  conftest.cpp -lLLVM-6.0    >&5
g++: error: unrecognized command line option '-Wcovered-switch-default'; did you
 mean '-Wno-switch-default'?
g++: error: unrecognized command line option '-Wstring-conversion'; did you mean
 '-Wint-conversion'?
`

**Comment by brobr** [comment]
OK, thanks. I can try the software now to find out ;-)
