### ISSUE TITLE
static binaries

### ISSUE THREAD

**Issue by KamilSJaron** [BoutrosLaboratory/bamql#15]
Hello,

I did not manage to install the tool on our cluster (CentOS 7). The problem occurred already during configuration, It complained about `configure.ac:8: error: possibly undefined macro: AC_PROG_LIBTOOL` which is probably about missing `glibtool` (at least first google hits suggest so). The tool looks nice (I am really sick of parsing bam files), but right now I would have to invest a lot to make it work (lot more than writing yet another python bam parser), therefore I wanted to ask...

Do you think it would be possible to share statically linked binaries withing GitHub releases? I know it's not informatically beautiful, but in bioinformatics reality, nothing really is.

**Comment by apmasell** [comment]
The package you are missing on CentOS is called `libtool`. I have tried to make static binaries, but been unsuccessful. `htslib` has a sprawling set of dependencies that makes building a static libraries impractical.
