### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by MPGiD** [BoutrosLaboratory/bamql#16]
Dear Boutroslab,

I am interested in using BAMQL for my research, however, I am running into a run error when trying ./bamql. 

I installed all the necessary software, but when I am trying to run bamql I receive the following error: "Error while loading shared libraries: libhts.so.2.to3part2: cannot open shared object file: No such files or directory."

However, I do have this file in /data/software/htslib. The software is probably scanning a different folder. Do you know which command I should change for this?

-Mark

**Comment by apmasell** [comment]
If you are on Linux, you can set the `LD_LIBRARY_PATH` environment variable to `/data/software/htslib/lib`, where the `libhts.so.2.to3part2` is located.
