### ISSUE TITLE
Getting the paired end read

### ISSUE THREAD

**Issue by virenar** [BoutrosLaboratory/bamql#17]
I am trying to use bamql to get both left aligned and right aligned read of a paired end read that matches a position and nucleotide. I am not able to write query that matches the request

Here is the syntax i am using right now
 bamql -f sample.bam -o select.bam 'chr(N) & nt_exact(NNN, X)'

Currently it sends only left aligned read. Let me know if there is functionality to get both left and right aligned read.

**Comment by apmasell** [comment]
`bamql-pairs` will get both reads in a pair if either one matches the read.

**Comment by virenar** [comment]
Thanks a lot for a quick response. It worked just fine.
