### ISSUE TITLE
Would it be possible binaries and / or to include this program in the bioconda repository?

### ISSUE THREAD

**Issue by arturomarin** [BoutrosLaboratory/bamql#20]
Hi!

I am developing a pipeline that I want to publish. For one of the parts it would be very interesting to be able to use bamql. I am developing the pipeline so that it can be used in both Linux and macOS, since many bioinformaticians use macOS. I think the bamql program can be somewhat complicated to compile for macOS. Would it be possible for you to distribute **executable binaries** of your program and/or include it in the **bioconda repositories**? I think this would also be interesting to facilitate the use of bamql in general.

Thank you so much,

**Comment by apmasell** [comment]
All these are permitted under the MIT licence.
