### ISSUE TITLE
configure forces -c++11 but bamql-1.6 and 1.6.1 evidently require -c++14

### ISSUE THREAD

**Issue by mmokrejs** [BoutrosLaboratory/bamql#26]
I am not able to compile current `git trunk` so I downloaded last two tagged releases. In `1.6` you dropped support for older `llvm` due to new syntax used. The configure fails for me complaining the code requires `-c++14` or `-gnu++14` but `configure.ac` forces `-c++11` everywhere. Was this overlooked in the past? After editing generated `configure` and replacing `-c++11` with `-c++14` I could make `configure` happy and generate `config.status`. Still compilation of the package fails for me later but it was a good move ahead.

Practically same happens with `1.6.1` source tree.

Provided `>=1.6` require llvm-14 I assume the `-c++11` is a leftover from the past?

**Comment by apmasell** [comment]
This has been fixed in the main branch. LLVM use to do really frustrating things with its flags, but they have updated.
